# Generated by Django 4.1.5 on 2023-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False),
        ),
    ]
